apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-2

nodeGroups:
  - name: worker 
    instanceType: t2.micro
    desiredCapacity: 2
    maxSize: 3
    minSize: 2
    tags:
      nodegroup-type: worker